%YAML:1.0
---
  # data
  dataset_dir: /home/chan/Documents/SLAM/slambook2/kitti/01

  # camera intrinsics
  camera.fx: 517.3
  camera.fy: 516.5
  camera.cx: 325.1
  camera.cy: 249.7

  num_features: 150
  num_features_init: 50
  num_features_tracking: 50